### ISSUE TITLE
Investigate IPLD block explorer data issues, create dependency tickets, and estimate story points to fix each issue

### ISSUE THREAD

**Issue by stellarmagnet** [vulcanize/ipld-block-explorer#33]
Categorize the issues into three buckets - 
(1) data available, just need to display it to close the issue 
(2) data not available because it's a non-consensus field / derived field (needs to be resolved by building new type of watcher)
(3) data available, just need mainnent/rinkeby block decoding, will be resolved once we properly decode rinkeby blocks

**Comment by Burmenska** [comment]
@stellarmagnet 
can you provide me with writing access pls?
I have admin access on GitHub but can't edit estimates and other info in tickets here

**Comment by ramilexe** [comment]
Categorize the issues into three buckets -

(1) data available, just need to display it to close the issue
 * Remove favicon #34

(2) data not available because it's a non-consensus field / derived field (needs to be resolved by building new type of watcher)
 * Block details - Miner is missing/null #25 - issue with geth-statediff(indexer) !!! Recheck 🔥
 * Transaction status - display errors #32 - need to call `eth_call` from ipld-eth-server. Need to bring ipld-eth-server to ipld-block-explorer stack and integrate with frontend.

(3) data available, just need mainnent/rinkeby block decoding, will be resolved once we properly decode rinkeby blocks
 * Block details - Block reward is incorrect #27 - geth-statediff
 * Ability to search by transaction hash #30 - needs to add graphql methods to watcher
 * Ability to search by block hash #29 - needs to add graphql methods to watcher
 * Ability to search by address #31 - needs to implement address watcher in eth-watcher-ts, and then implement frontend part
